### github action to make and publish a release
##
name: "CTAN upload validation"

## Controls when the workflow will run
on:
  ## Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

## A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # 1. checkout the repo
      - name: "checkout"
        uses: actions/checkout@v2

      # 2. create package for testing
      - name: "create an old tikz-trackschematic package"
        run: ./build.sh --non-interactive --release v0.7.0

      # 3. 
      - name: CTAN submit validation
        uses: paolobrasolin/ctan-submit-action@v1
        with:
          file_path: tikz-trackschematic-v0.7.0.zip
          version: 1.1
          action: validate
          fields: |
            pkg: "tikz-trackschematic"
            summary: "A TikZ library for creating track diagrams in railways"
            description: "This TikZ library is a toolbox of symbols geared primarily towards creating track schematic for either research or educational purposes. It provides a TikZ frontend to some of the symbols which may be needed to describe situations and layouts in railway operation. The library is divided into sublibraries: topology, trafficcontrol, vehicles, constructions, electrics, symbology, and measures."
            license: isc
            repository: https://github.com/railtoolkit/tikz-trackschematic
            author: "Martin Scheidt"
            uploader: "Martin Scheidt (via github CI)"
            email: m.scheidt@tu-braunschweig.de
            update: true
            version: v0.7.0
