# This is a basic workflow to help you get started with Actions

name: debug

# Controls when the workflow will run
on:
  push:
    branches: [ github-action ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  debug:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "checkout"
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2

      - name: "update runner"
        run: sudo apt-get update -y && sudo apt-get upgrade -y imagemagick

      #   ##
      # - name: "setup TeX Live (via apt-get)"
      #   # old TeX Live version: 2019
      #   run: |
      #     sudo apt-get update -y || sudo apt-get update -y || sudo apt-get update -y
      #     sudo apt-get install -y texlive-latex-base || sudo apt-get install -y texlive-latex-base || sudo apt-get install -y texlive-latex-base
      #   ##
      # - name: "setup TeX Live (via DanySK)"
      #   # old TeX Live version: 2019
      #   uses: DanySK/setup-texlive-action@master
      #   with:
      #     requirements-file: .github/tex/packages.test.txt
      #   ##
      # - name: "setup TeX Live (via teatimeguest)"
      #   # tlmgr needs updates and fails
      #   uses: teatimeguest/setup-texlive-action@v1
      #   with:
      #     package-file: .github/tex/packages.test.txt
      #   ##
      - name: "setup TeX Live (via paolobrasolin)"
        uses: paolobrasolin/setup-texlive-action@v1
        with:
          profile-path:  ${{ github.workspace }}/.github/tex/texlive.profile.txt
          packages-path: ${{ github.workspace }}/.github/tex/packages.test.txt

      - name: "install tikz-trackschematic"
        run: chmod +x dev-install.sh && ./dev-install.sh -b

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: railtoolkit,kaat0
