# This is a basic workflow to help you get started with Actions

name: "continuous integration test"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'CITATION.cff'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - '.github/workflows/cffvalidation.yaml'
      - '.github/workflows/debug.yaml'
      - '.github/workflows/release.yaml'
      - '.github/workflows/zenodo.yaml'
      - '.github/zenodo/*'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'CITATION.cff'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - '.github/workflows/cffvalidation.yaml'
      - '.github/workflows/debug.yaml'
      - '.github/workflows/release.yaml'
      - '.github/workflows/zenodo.yaml'
      - '.github/zenodo/*'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "checkout"
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3

      - name: "install ghostscript"
        run: sudo apt-get install -y ghostscript
        
      - name: "setup TeX Live (via paolobrasolin)"
        uses: paolobrasolin/setup-texlive-action@v1
        with:
          profile-path:  ${{ github.workspace }}/.github/tex/profile.basic.txt
          packages-path: ${{ github.workspace }}/.github/tex/packages.test.txt

      - name: "test tikz-trackschematic"
        run: ./build.sh --non-interactive --test --verbose
